# Generated by Django 5.0.7 on 2024-08-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="hashed_value",
            field=models.CharField(
                db_index=True, default="ffeefce03cfd8c33bfcc465f01dd2047"
            ),
        ),
    ]
