# Generated by Django 5.0.7 on 2024-08-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "hashed_value",
                    models.CharField(
                        db_index=True,
                        default="1116bef4757bb3cbf4efa6dad4e0f695",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("is_dm", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Channel",
                "verbose_name_plural": "Channels",
            },
        ),
    ]
