# Generated by Django 5.0.7 on 2024-08-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat_channel", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatchannel",
            name="hashed_value",
            field=models.CharField(
                db_index=True,
                default="4ba9b29ef457cea5b670c45fe2ffdb73",
                max_length=64,
                unique=True,
            ),
        ),
    ]
